### ISSUE TITLE
Cannot Load Map

### ISSUE THREAD

**Issue by salvonos** [Ayushanbhore/Unreal-Quest3-PassthroughSample#1]

**Comment by salvonos** [comment]
when I try to open the project it failes saying '.umap file failed to load as it appears to be an asset'.
how to solve this? 
the map is not showing in the content browser

**Comment by Ayushanbhore** [comment]
Hi Salvonos,

I have fixed the issue you were facing which was of LFS.  I have removed the LFS and made it GIT friendly. Please re-clone or re download the repository for start making your Mixed Reality projects in Unreal Engine for Quest 3 or Quest Pro. Let me know if you have more questions or issues and please don't forget to star this.

Sincerely 
Ayush

**Comment by Ayushanbhore** [comment]
Hi, it has been fixed now. Thanks for notifying me
