### ISSUE TITLE
App Crash at launch

### ISSUE THREAD

**Issue by notraore** [Ayushanbhore/Unreal-Quest3-PassthroughSample#4]
Hey @Ayushanbhore,

just tested the app on my Meta Quest 3 and i'm having an issue -> The app crash at launch

I don't know if the app work only for Quest Pro

Did you try it on Quest 3 ?

**Comment by Ayushanbhore** [comment]
Dear @notraore,

This project was specifically designed for the Meta Quest 3, and it has been thoroughly tested on that platform. Now, I would appreciate it if you could provide details about the Android settings you are using to build for the Quest 3. It's important to ensure that we are using compatible settings, as an incompatible APK might lead to functionality issues.

Well, I am working on a newer repository with more toolkits like Passthrough, Scene and the latest Mesh API Development exclusively for meta Quest 3 which will go live in next three days which will be surely be an upgrade to this project. So try fixes in the mean time and once it goes live you can use that to create your Mixed Reality Apps.

Thank you!

**Comment by notraore** [comment]
Hey @Ayushanbhore,

Oh, ok so maybe there's something wrong with my setting.
So for more details I'm building Android_ASTC


Here is the MetaXR settings : 
![UnrealEditor_AxJfmc08RG](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/dd55dee6-a656-477a-ace8-bb0a6e7379ec)

Here is the android SDK settings :
![UnrealEditor_dSZIvvYn27](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/0857caa2-60ae-464a-9524-7bd021979838)

Here is my Android build settup :
![UnrealEditor_y7sbK6BDO2](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/52917667-315b-4ef5-9579-cac10509bc18)

I already had an issue before (With Quest 2) with Vulkan that used to crashed and I thought it could be it, but OpenGL/ES3.2 doesn't compile.

If you need more infos I can provide more screenshot

I'll be more than happy to test your new repository when it goes live ! Looking forward to create XR App

Thank you for your answer and thank you to provide tools like this 👍

**Comment by notraore** [comment]
Hey @Ayushanbhore,

Oh, ok so maybe there's something wrong with my setting.
So for more details I'm building Android_ASTC


Here is the MetaXR settings : 
![UnrealEditor_AxJfmc08RG](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/dd55dee6-a656-477a-ace8-bb0a6e7379ec)

Here is the android SDK settings :
![UnrealEditor_dSZIvvYn27](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/0857caa2-60ae-464a-9524-7bd021979838)

Here is my Android build settup :
![UnrealEditor_y7sbK6BDO2](https://github.com/Ayushanbhore/Unreal-Quest3-PassthroughSample/assets/27351943/52917667-315b-4ef5-9579-cac10509bc18)

I already had an issue before (With Quest 2) with Vulkan that used to crashed and I thought it could be it, but OpenGL/ES3.2 doesn't compile.

If you need more infos I can provide more screenshot

I'll be more than happy to test your new repository when it goes live ! Looking forward to create XR App

Thank you for your answer and thank you to provide tools like this 👍

**Comment by meba84a6** [comment]
Hi. Very cool project. I see you have a newer version coming out and I would like to help test that out. 

I have the same issue of crashing on quest 3 on launch of the app in quest 3. What unreal version, android version, java, api levels and build tools do you use? It would be helpful to know and use exactly the same versions as you (all the android studio settings, and unreal version). 

The Meta XR plugin version "Preferably - 54.0 Version" would not work with unreal 5.1 so I used the Meta XR 51 version.  I tried android-33, android-26 and now I'm going to try android-23.  Again, it would helpful to get all the android studio settings and the "SetupAndroid.bat" for unreal engine and any project settings I might have to change).  I used UE5.1 because you listed it but the plugin you suggested to use didn't work so I assume you're not using UE5.1 

Windows 11
Quest 3
Unreal 5.1
Sidequest to transfer files to quest 3

**Comment by ghost** [comment]
Hi, I had the same issue of the quest 3 app crashing at launch.  I followed the instructions at the link below and was able to run the app with no problem in Unreal 5.2.  

https://communityforums.atmeta.com/t5/Quest-Development/UE5-2-1-Had-some-problems-building-to-Quest-3-and-VR-Preview/m-p/1094678

I had to sign up on oracles website and download the correct java and install it. Then point to the C:\Program Files\Java\jre1.8.0_202\ folder for JAVA in unreal and also I had to copy the tools.jar file from C:\Program Files\Android\Android Studio\jre\lib.  

I also had to change the environment setting for JAVA to point to C:\Program Files\Java\jre1.8.0_202.  Windows key/settings/system/about/ click the advanced system settings then environment variables.

**Comment by notraore** [comment]
@meba84a6  Thank you for your help ! I'll try that now !

**Comment by notraore** [comment]
@meba84a6 Enabling MetaXR + OpenXR plugin seems to cause the crash.

I'll investigate more into it today
